/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-nrsc5_rx
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_NRSC5_RX_API_H
#define INCLUDED_NRSC5_RX_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_nrsc5_rx_EXPORTS
#define NRSC5_RX_API __GR_ATTR_EXPORT
#else
#define NRSC5_RX_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_NRSC5_RX_API_H */
