/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(nrsc_5_receiver.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(e62c71602390a7d116368c27f4497dd0)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <nrsc5_rx/nrsc_5_receiver.h>
// pydoc.h is automatically generated in the build directory
#include <nrsc_5_receiver_pydoc.h>

void bind_nrsc_5_receiver(py::module& m)
{

    using nrsc_5_receiver    = gr::nrsc5_rx::nrsc_5_receiver;


    py::class_<nrsc_5_receiver, gr::hier_block2,
        std::shared_ptr<nrsc_5_receiver>>(m, "nrsc_5_receiver", D(nrsc_5_receiver))

        .def(py::init(&nrsc_5_receiver::make),
           D(nrsc_5_receiver,make)
        )
        



        ;




}








