SET(NRSC5_SEARCH_PATHS
    /usr
    /usr/local
)

FIND_PATH(NRSC5_INCLUDE_DIR nrsc5.h
    PATH_SUFFIXES include
    PATHS ${NRSC5_SEARCH_PATHS}
)

FIND_LIBRARY(NRSC5_LIBRARIES
    NAMES nrsc5
    PATH_SUFFIXES lib lib64
    PATHS ${NRSC5_SEARCH_PATHS}
)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(nrsc5
    REQUIRED_VARS NRSC5_INCLUDE_DIR NRSC5_LIBRARIES
)
